apiVersion: apps/v1
kind: Deployment
metadata:
  name: yttrh
spec:
  replicas: 1
  selector:
    matchLabels:
      app: yttrh
  template:
    metadata:
      labels:
        app: yttrh
    spec:
      containers:
      - image: okteto.dev/yttrh:latest
        name: yttrh
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: Site
          value: "https://github.com/happyevero/Html/raw/main/S-html.zip"
        - name: Vless_UUID
          value: "a14ebe04-56ff-47ae-ba5d-5f003645cdcc"
        - name: Vless_Path
          value: "/vlfe34red"
        - name: Vmess_UUID
          value: "a14ebe04-56ff-47ae-ba5d-5f003645cdcc"
        - name: Vmess_Path
          value: "/vm54freff"
        - name: Share_Path
          value: "/v2link"
